### ISSUE TITLE
Update arguments for authors in `setup_package()`

### ISSUE THREAD

**Issue by henriquesposito** [globalgov/qData#127]
Giving all first names and then surnames may create a bit of confusion. Update argument so that name and surname are given together.

**Comment by henriquesposito** [comment]
Roles are also given altogether. Update `setup_package()` so that roles also becomes an argument in the function.

**Comment by henriquesposito** [comment]
@BBieri when you have some time next week, can we take a quick look at this issue together? We need to simplify the author argument to take and treat one name input and, then, split into two. As well as allow for role to be declared as part pf the argument. I have a few  ideas on how to do this but, since you have set up the new arguments for `setup_package()` as well as added the `new_author()` function, I thought I would discuss them with you first to find the best way. Thank you.

**Comment by BBieri** [comment]
@henriquesposito I decided to go this route because authors may have more than one name and/or more than one surname. Thus, simply splitting the string where there is a blank space won't do it, unfortunately. Let me know if you have any ideas on rules that are able to systematically differentiate between a second last name and a first surname. 

As for the roles, I implemented them in the `new_author()` function but not the `setup_package()` function since they were already in the template. I'll enable it to be set from the `setup_package()` function directly this morning.

**Comment by BBieri** [comment]
Just pushed the updated version of the `setup_package()` function.

**Comment by henriquesposito** [comment]
Thank you for the help with roles @BBieri ! Just one feedback on it, perhaps we do not want to stop if no role is declared and, instead, we just give a "ctb" id no role is declared. What do you think? I tried to implement this, but you can go back if you want to. I think we can also simplify the way in which roles are assigned in the function by doing so.  

On another note, I worked on the function this morning and the function now accepts one author argument and multiple last names. That is, I removed the surname argument and updated how the author names argument works so that it takes multiple authors with a varied number of names and sorts it out into given and family names to be applied in the different templates. I tried to keep the updates as consistent as possible with the function. 

Could you please take a look at the function and let me know what you think? There might be some issues arising from this, but I am confident this solutions will work and is definite for the author's name issues we have been having with `setup_package()`
