### ISSUE TITLE
Create a new `code_agreements()` function

### ISSUE THREAD

**Issue by henriquesposito** [globalgov/qData#130]
The function should programmatically create meaningful naming conventions from long agreement tittles and refer to repo/sql file for names and updates.

**Comment by EstherPeev** [comment]
[https://app.zenhub.com/files/291753904/324f4c7c-5669-4eaf-8b85-c5ecc251df46/download](https://app.zenhub.com/files/291753904/324f4c7c-5669-4eaf-8b85-c5ecc251df46/download)

Please find above the link to the first pdf draft of the codebook that summarizes how we could code the ID for the different treaty types in qEnviron(and for other q packages later). It gives an overview and a target of how IDs should look like in the qPackages ecosystem. 

@jhollway and @henriquesposito 
Please let me know if you have any suggestions.

**Comment by henriquesposito** [comment]
Thank you Esther, really nice work. It is good to visualize these things to get a better idea of how to proceed. 

I have two suggestions. 

First, maybe for bilateral treaties we can use a B followed by A (agreement), P (protocol) or E (amendment), two letter abbreviation for countries and issue-domain. We could remove year since dates are going to also be present on the following columns. For the example you gave (Agreement Between Mexico And The Federal Republic Of Germany On The Elimination Of Special Waste In Mexico, DF
Project) it would become BA_MX_DE_Waste. 

Second, for multilateral treaties we can use M B followed by A, P, E and issue-domain. That means for the example you gave (Amendments To The Benelux Convention On The Hunting And Protection Of Birds) it would become ME_Hunting. Though we may add city signed if we have this data easy, although this is not always part of the treaty tittle and might be confusing I realize. 

Let me know what you think. Thank you once again for this.

**Comment by jhollway** [comment]
Really good @EstherPeev . Below a few comments for our further discussion:

- I prefer three letter state codes (ISO-3166-alpha3) to two letter codes because they are (usually) more unambiguous for human readers
- I prefer dashes to underscores to indicate relations between two actors or institutions
- if bilateral agreements are written e.g. `MEX-DEU`, then do we need to state that it is a `B`, bilateral? Perhaps, if we expect users to use labels to subset to just bilaterals or multilaterals, but I guess we'd also offer this information in another column. The only reason to include it in the label/ID is to make it easier to distinguish, as a human or machine, two agreements...
- are successive agreements, protocols or amendments numbered incrementally (e.g. `MEX-DEU_E1`, `MEX-DEU_E2`) or are they appended with a date? To avoid 
- I fear that while some agreements will have a clear topic/issue, etc, for others it will be more ambiguous or they will cover multiple topics. Moreover, while you have helpfully identified a topic code for the environment, what about topics beyond the environment?
- we may get multiple multilateral agreements that are really in the same lineage, but each have recognised abbreviations. (How) Should we reveal this association in the IDs?

**Comment by EstherPeev** [comment]
[https://app.zenhub.com/files/291753904/312fab68-c932-4309-b622-097307da1592/download](https://app.zenhub.com/files/291753904/312fab68-c932-4309-b622-097307da1592/download)

@jhollway 
Please find here the 2nd draft in which I integrated the comments made above. I have few comments to add to respond to both of your feedback: 

* I left the abbreviation that specifies the main topic of the treaty. In your suggestion @henriquesposito, you would like to put a key word found in the treaty title instead? (put "Hunting" instead of "SPE"). We can either pick one key word from the title or used the different categories I have listed. This would mean I will have to create few more categories for qHealth and qTrade, etc. The other option is to only put "E" which refers to environment followed by a number.
* I have changed the ID in order to add the information of the existence of any lineage with other treaties. 
* Should we keep the date for the "known" treaty? (e.g. CBD_1992)

I would be happy to hear any comments/suggestions both of you may have.

**Comment by jhollway** [comment]
Thanks @EstherPeev , you and @henriquesposito will see that I've started development on a `code_agreements()` function in a separate branch. Please elaborate the coding scheme in terms of programming code there.

**Comment by henriquesposito** [comment]
Thank you @EstherPeev, I really like the changes and think things are coming together. Good job. 

- I actually like the topic category rather than a key word. We will need to code a dictionary of terms for each category though, and what to do when two categories overlap in an agreement tittle. 
- I like the lineage changes with the unique ID and the ordering numbers after the agreement type.
- We might want to drop the dates for known treaties for consistency. 

Now let's work on the function!

**Comment by jhollway** [comment]
In `{gnevar}` we explored having the "lineage" of a treaty being defined based on the conjunction of the activity being governed, e.g. "fishing", "water pollution", etc., and the area of governance, e.g. "Rhine", "Antarctic", "global", etc. We'd need to work on large (and extensible) category lists for this to work though, and some of these codes won't be revealed in the titles themselves..

**Comment by henriquesposito** [comment]
The function and helper functions have been setup and work. There are still some fixes, updates and re-thinking left to do. A new issue will be open for these.
