### ISSUE TITLE
Develop code_agreements() so that it more accurately creates a qID 

### ISSUE THREAD

**Issue by henriquesposito** [globalgov/qData#148]
There is some re-thinking to do with code_agreements() now that the function is set up.

- Find a better way to assign (shorter) unique IDs
- Extract number of protocol or amendment
- Address some of the cases which are still not matching
- Expand and develop name matching for known agreements and to find duplicates
- Look into the `consolidate()` function for reference/inspiration

**Comment by EstherPeev** [comment]
Other few issues to work on:  

* Around 6-7% of the IDs are duplicates. While most of them are amendment/protocol signed on the same date and linked to the same treaty (which could be resolved by extracting the number of the amendment/protocol), others are fake duplicates. See the example below. Both treaties have the same ID (JPN-RUS-FIS19760928)

![image.png](https://images.zenhubusercontent.com/5ff2de14fb5a58fc49c60af6/4dfd2612-56bd-4093-82a8-839e46bcd1e1)
![image.png](https://images.zenhubusercontent.com/5ff2de14fb5a58fc49c60af6/36d9f2c5-e76b-40dc-893e-a57d4bc282ee) 

* The second issue is when a treaty does not have any "Beg" date. The function currently put NA instead of the uID. A random number could be assigned in that case?

**Comment by jhollway** [comment]
These are 'good' issues. 

The first issue might be solved if we make the 'lineage' variable a combination of area and activity, as we discussed. This would make the first agreement SouthernHemisphere-Whaling (or something similar) and the second agreement NorthPacific-Whaling (or something similar).

The second issue either points to how important a beginning date is for `code_agreements()` to work, or I would suggest in the case that there really is just no beginning date, then this is either because it was never signed in the end (i.e. 9999-12-31) or there is complete ambiguity as to the signature date (i.e. we know it was signed, but have no idea when), in which case some kind of range should be given and then the qID code should reflect that range somehow.

**Comment by EstherPeev** [comment]
One important issue with the new qID coding scheme appeared when code_agreements() has been tested on CIESIN. All the dates in this dataset are under a range format because CIESIN only provides the year of signature and entry into force (no day or month) of the treaties. All agreements signed the same year happened to have the same qID, same for protocols or amendments. Half of the generated qID in the dataset are duplicates.

**Comment by jhollway** [comment]
Great spotting @EstherPeev. Can you open up a new issue for this?

**Comment by henriquesposito** [comment]
Great @EstherPeev , can you also add tests for this issue with the other tests for code_agreements() function? Thank you.
