### ISSUE TITLE
Break Gordian knot of interpackage dependencies

### ISSUE THREAD

**Issue by jhollway** [globalgov/qData#165]
qData > qStates, qCreate
qCreate > qData, qStates
qStates > qData
qEnviron > qData, qStates

**Comment by henriquesposito** [comment]
I updated some of the package dependencies, but it is still a bit of a knot... 

Now the dependencies are as follows:

qData > qStates 
(under suggested section in description and necessary for examples in report_data family of functions)

qCreate > qStates, qEnviron 
(besides examples, qStates is actually called in code_agreements() to code parties to a treaty and package is listed under dependencies; while qEnviron is used for examples for code_agreements() and is suggested in description)

As for qStates and qEnviron they do not depend on any of the other qPackages know. 

@jhollway Please let me know what you think or if you would like this to be altered. Thank you.

**Comment by jhollway** [comment]
There needs to be no GitHub dependencies for qData at least. Either there will need to be no examples for report_data or we point to an external example.

**Comment by henriquesposito** [comment]
I removed qStates as a dependency for qData. 

To do so, I updated `get_packages()` to load qPackages after downloading them. This way, once we add the function before the examples, they run even without the dependency. I do not know if this is the best solution, it is a bit slow and, after a while, GitHub does not allow to get information without an API, but it was implemented for now.

For now, though, all examples that require outside packages were commented out with `\dontrun{}`. Otherwise, we can either remove examples from `report_data()` and `consolidate()` or point to external examples, as suggested.
