### ISSUE TITLE
Set up more informative README

### ISSUE THREAD

**Issue by jhollway** [globalgov/qData#32]
README.Rmd can be compiled and updated automatically: https://github.com/r-lib/actions/tree/master/examples#render-readme

**Comment by henriquesposito** [comment]
I do not know if this helps at all, but here is a preview of the first draft README.rmd document I prepared in pdf. I also have an .rmd file for it, which I can send by email if you would like since the file format is not supported here.[https://app.zenhub.com/files/291753904/44d2e608-fa8f-4269-b66f-21550528f58e/download](https://app.zenhub.com/files/291753904/44d2e608-fa8f-4269-b66f-21550528f58e/download)
