### ISSUE TITLE
Create data report function

### ISSUE THREAD

**Issue by jhollway** [globalgov/qData#78]
Should outline:

- [x] number of databases/cubes in the package
- [x] names of the datasets in each database
- [x] number of observations in each dataset
- [x] number of variables in each dataset
- [x] amount of missing in each dataset
- [x] sources of each dataset

**Comment by EstherPeev** [comment]
I made one commit in which the function `report_data()` is created and shows the number of unique ID, missing data, the number of rows and columns for each dataset within the database. I will certainly have to adapt it to qEnviron because it has multiple databases. Also, I will try to find a solution to integrate dates in the table. For now, I have commented out the lines that refer to dates (Beg and End).
