### ISSUE TITLE
Install/update packages from get_packages() by number listed

### ISSUE THREAD

**Issue by jhollway** [globalgov/qData#79]

**Comment by henriquesposito** [comment]
For now that we only have two packages in the ecosystem, typing the respective number by which a package is listed in the tibble will also work to install/update the package. However, this may need to be updated as more packages are added from different users/organizations.

**Comment by henriquesposito** [comment]
@jhollway For the qStates and qEnviron packages there is no about description on their GitHub and, thus, the description column returns NA in the tibble when running `get_packages()`. The tibble currently returned looks as if the function is not properly working due to the NAs though it seems that I do not have permission to change these about description. Should we change these to a short sentence that describes the package? Thank you.
