### ISSUE TITLE
Create `new_author()` function

### ISSUE THREAD

**Issue by EstherPeev** [globalgov/qData#90]
The function should append an existing description file to include new authors as they are added during the package development process.

**Comment by jhollway** [comment]
See `desc::desc_add_author()`

**Comment by jhollway** [comment]
Add ability to add new authors, contributors, or data contributors by ORCID id?

**Comment by BBieri** [comment]
Created two new functions; `new_author` and `new_author_orcid`. Both rely on the `{desc}` package and unfortunately experience a bug whereby one cannot set more than one element in the comment line. 

This issue is known and has been created on the `{desc}` package but has not yet been resolved. See [this](https://github.com/r-lib/desc/issues/91).
