### ISSUE TITLE
`standardise_dates()` function is not working with some date columns 

### ISSUE THREAD

**Issue by EstherPeev** [globalgov/qData#95]
In some cases, `standardise_dates()` works only when a date variable is split in three columns (year, month and day). In other cases, this does not work. This happens regardless of the date formats of date variables in some cases.

**Comment by henriquesposito** [comment]
Example of issue back trace. 

```r

> GNEVA <- as_tibble(GNEVAR) %>%
+   transmutate(Beg = standardise_dates(DocSign),
+          End = standardise_dates(DocEnd),
+          ID = GENG) %>%
+   dplyr::arrange(Beg, ID)
Error: Problem with `mutate()` input `Beg`.
x missing value where TRUE/FALSE needed
i Input `Beg` is `standardise_dates(DocSign)`.
Run `rlang::last_error()` to see where the error occurred.
In addition: There were 16 warnings (use warnings() to see them)
> rlang::last_error()
<error/dplyr:::mutate_error>
Problem with `mutate()` input `Beg`.
x missing value where TRUE/FALSE needed
i Input `Beg` is `standardise_dates(DocSign)`.
Backtrace:
  1. `%>%`(...)
 17. base::.handleSimpleError(...) C:/Users/h-spo/Documents/GitHub/qData/R/standardise_dates.R:139:4
 18. dplyr:::h(simpleError(msg, call))
Run `rlang::last_trace()` to see the full context.
> rlang::last_trace()
<error/dplyr:::mutate_error>
Problem with `mutate()` input `Beg`.
x missing value where TRUE/FALSE needed
i Input `Beg` is `standardise_dates(DocSign)`.
Backtrace:
     x
  1. +-`%>%`(...)
  2. +-dplyr::arrange(., Beg, ID)
  3. +-qData::transmutate(...)
  4. | +-dplyr::mutate(.data, ...) %>% dplyr::select(-dplyr::one_of(vToRemove)) C:/Users/h-spo/Documents/GitHub/qData/R/wrangling.R:34:2
  5. | +-dplyr::mutate(.data, ...)
  6. | \-dplyr:::mutate.data.frame(.data, ...)
  7. |   \-dplyr:::mutate_cols(.data, ...)
  8. |     +-base::withCallingHandlers(...)
  9. |     \-mask$eval_all_mutate(dots[[i]])
 10. +-dplyr::select(., -dplyr::one_of(vToRemove))
 11. +-qData::standardise_dates(DocSign)
 12. | +-lubridate::as_date(unlist(lapply(dates, function(x) date_disambig(x)))) C:/Users/h-spo/Documents/GitHub/qData/R/standardise_dates.R:187:2
 13. | +-base::unlist(lapply(dates, function(x) date_disambig(x))) C:/Users/h-spo/Documents/GitHub/qData/R/standardise_dates.R:187:2
 14. | \-base::lapply(dates, function(x) date_disambig(x)) C:/Users/h-spo/Documents/GitHub/qData/R/standardise_dates.R:187:2
 15. |   \-qData:::FUN(X[[i]], ...)
 16. |     \-qData:::date_disambig(x) C:/Users/h-spo/Documents/GitHub/qData/R/standardise_dates.R:187:2
 17. \-base::.handleSimpleError(...) C:/Users/h-spo/Documents/GitHub/qData/R/standardise_dates.R:139:4
 18.   \-dplyr:::h(simpleError(msg, call))

```

**Comment by EstherPeev** [comment]
So the function is working correctly when 3 arguments are used like below: 

```r
standardise_dates(Year, Month, Day)
```
But an error appears when only one argument is used: 

```r
standardise_dates(Signature)
```

So the temporary solution is that the variable "Signature" is divided into 3 columns (Year, Month, Day) and then the function `standardise_dates()` will work.

**Comment by jhollway** [comment]
But this is a bug that @henriquesposito should be able to fix

**Comment by henriquesposito** [comment]
For some datasets `standardise_dates()` works correctly for 1 column, as is the case for the datasets on qStates. While for some other datasets in qEnviron there is a need to split the dates into three variables so that `standardise_dates()` work.  However, for some date variables, splitting into three columns does not solve the issue (as for GNEVAR$agreements) and date variable, even split in three, produces the same error. Me and Esther are looking into this issue and what exactly is causing it so that we can properly address it as fast as possible. Thank you.

**Comment by henriquesposito** [comment]
After some research, it appears that the error means that the evaluation of the comparison produced an NA value in `standardise_dates()` instead of TRUE or FALSE (see https://www.biostars.org/p/336707/`). I have tried to reproduce the issue in a test developed for `standardise_dates()` in qData and indeed there seems to be an issue with how the function deal with multiple (and inconsistent) date values. There are two connected issues I can think of that may be causing this error (but I might be wrong) they are:

1- the if statements in the function do not take vector inputs well and returns the warnings even when the function runs
2- the NA or missing values are not being taken correctly and the functions does not know how to operate these

I am trying to address the issue the best I can.

**Comment by henriquesposito** [comment]
@EstherPeev Thank very much for all your help with this bug yesterday and today. 

As of right now, I am rebuilding the function with ifelse statements to deal better with vector inputs. Some of the functionality will take a bit more time to add back to `standardise_dates()`. I have started to push some changes to the function now but @EstherPeev we can pick up tomorrow and try tackle this bug now that we know what is causing it as well as a way around it.
