### ISSUE TITLE
Reduce number of dependencies to under 20 packages

### ISSUE THREAD

**Issue by jhollway** [globalgov/qData#96]
Suggest moving some to suggest and use them conditionally

**Comment by henriquesposito** [comment]
Related to this issue, xfun is relied upon for the `get_packages()` function to work. However, currently it is a suggested package and not a dependency which can sometimes cause an issue for users.

**Comment by henriquesposito** [comment]
@BBieri should we address this issue by privileging dependencies on user functions rather than developer functions? We can move some of the dependencies exclusively used in the developer functions under suggests in the description, since people who use the developer functions are likely to be more R savvy than "regular" users. we can make a note about the suggested packages in the developer's vignette in this case. What do you think? Do you have

**Comment by jhollway** [comment]
I'm not sure about the implications for testing, but what we could do is add (conditional) installation of additional packages required for qPackage creation to `setup_package()`?

**Comment by henriquesposito** [comment]
I think we can do that as well, it is perhaps a better way, you are right. 

There are two ways of doing this, if I understand correctly. One, we can write a function for installing/loading required packages under suggest when using some of our functions. Or, alternatively, we can use `pacman::p_load()` function to do so. Both options would require to add lines at the top of the scripts for the selected functions. The `{pacman}` option appears to require less effort and be more elegant. Of course, that would imply adding `{pacman}` as an import so that we can move several packages under suggests in the description. 

What do you think @jhollway?

**Comment by jhollway** [comment]
Well, we already have the `depends()` function... Do we really need the `{pacman}` dependency?

**Comment by henriquesposito** [comment]
Actually, I have played around with `depends()` and with `pacman::p_load()` and they generate very weird errors when running R CMD checks if they are added to functions and dependencies are moved around. I will keep on looking into possible solutions for this.

**Comment by henriquesposito** [comment]
This should no longer be an issue (for the near future) with the qData package being split into two packages.
